version: '3'
services:
  website:
    image: nginx:latest
    container_name: www.rossetto.ovh
    ports:
      - "50000:80" # Reindirizza la porta 80 dell'host al container
    volumes:
    - ./src:/usr/share/nginx/html
    restart: unless-stopped


# To update the website:
# 1) cd Desktop/Portfolio
# 2) docker-compose down
# 3) cd /home/jaco/Desktop
# 4) sudo rm -r Portfolio
# 5) git clone https://github.com/jacoporossetto/Portfolio.git
# 6) cd Portfolio
# 7) docker-compose up -d