version: '3'
services:
  website:
    image: nginx:latest
    container_name: www.rossetto.ovh
    volumes:
      - ./src:/usr/share/nginx/html
    expose:
      - "80"  # Il sito web è esposto sulla porta 80 all'interno del container
    restart: unless-stopped

  reverse-proxy:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"  # Reindirizza la porta 80 dell'host al container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Configurazione personalizzata di Nginx
    restart: unless-stopped


# To update the website:
# 1) cd Desktop/Portfolio
# 2) docker-compose down
# 3) cd /home/jaco/Desktop
# 4) sudo rm -r Personal-Website
# 5) git clone https://github.com/MrPanda376/Personal-Website
# 6) cd Personal-Website
# 7) docker-compose up -d